services:
  nginx:
    image: nginx:1.25-alpine
    container_name: nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend
    networks:
      - app_net
    restart: unless-stopped

  frontend:
    build:
      context: ../../frontend
      dockerfile: deploy/Dockerfile
    container_name: frontend
    expose:
      - '80'
    networks:
      - app_net
    restart: unless-stopped

  backend:
    build:
      context: ..
      dockerfile: deploy/backend/Dockerfile
    container_name: backend
    environment:
      NODE_ENV: production
      PORT: 8000
      REDIS_HOST: redis
      REDIS_PORT: 6379
    expose:
      - '8000'
    depends_on:
      - redis
    networks:
      - app_net
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis
    networks:
      - app_net
    restart: unless-stopped

  jenkins:
    build:
      context: .
      dockerfile: ./jenkins/Dockerfile
    container_name: jenkins
    user: root
    networks:
      - app_net
    environment:
      - TZ=Asia/Seoul
    volumes:
      - jenkins_data:/var/jenkins_home
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  swagger:
      image: swaggerapi/swagger-ui:latest
      container_name: swagger
      environment:
        - URL=/spec/openapi.yaml
        - BASE_URL=/
      volumes:
        - ./swagger/public:/usr/share/nginx/html/spec:ro
      expose:
        - '8080'
      networks:
        - app_net
      restart: unless-stopped

networks:
  app_net:
    driver: bridge

volumes:
  jenkins_data:
