server {
  listen 80;
  server_name gsrelay.o-r.kr;

  location / {
    return 301 https://$host$request_uri;
  }
}

server {
  listen 443 ssl;
  server_name gsrelay.o-r.kr;

  ssl_certificate     /etc/letsencrypt/live/gsrelay.o-r.kr/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/gsrelay.o-r.kr/privkey.pem;

  location / {
    proxy_pass http://frontend;
    proxy_http_version 1.1;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location /api {
    proxy_pass http://backend:8000;
    proxy_http_version 1.1;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
  }
}

server {
  listen 80;
  server_name jenkins.gsrelay.o-r.kr;

  location / {
    return 301 https://$host$request_uri;
  }
}

server {
  listen 443 ssl;
  server_name jenkins.gsrelay.o-r.kr;

  ssl_certificate     /etc/letsencrypt/live/jenkins.gsrelay.o-r.kr/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/jenkins.gsrelay.o-r.kr/privkey.pem;

  location / {
    proxy_pass http://jenkins:8080;
    proxy_http_version 1.1;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Port 443;
  }
}
